name:                graph
version:             0.4.1.1
github:              "tosku/graph"
license:             GPL-3
author:              "Thodoris Papakonstantinou"
maintainer:          "hi@tpapak.com"
copyright:           "Thodoris Papakonstantinou, 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Graph library using adjacency list representation
category:            Graph theory

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tosku/graph#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - mtl >= 2.2.1
  - natural-numbers >= 0.1.2.0
  - containers >= 0.5.10.2
  - text >= 1.2.2.2
  - Unique >= 0.4.7.9
  - either-unwrap >= 1.1
  - async >= 2.1.1
  - binary >= 0.8.6.0
  #exposed-modules:     Data.Graph.AdjacencyList
                     #, Data.Graph.AdjacencyList.Grid
                     #, Data.Graph.AdjacencyList.Network
                     #, Data.Graph.AdjacencyList.BFS
                     #, Data.Graph.AdjacencyList.DFS
                     #, Data.Graph.AdjacencyList.WFI
                     #, Data.Graph.AdjacencyList.Metrics
                     #, Data.Graph.AdjacencyList.PushRelabel.Internal
                     #, Data.Graph.AdjacencyList.PushRelabel.Pure

tests:
  meta-springs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7 && <5
    - tesths >= 0.1.1.0
    - graph
    - Unique
    - fgl >= 5.5.3.1
    - containers >= 0.5.10.2
    - vector
    - ansi-terminal
    - binary >= 0.8.6.0
