flags: {}

resolver: lts-18.18

packages:
- .
extra-deps:
- natural-numbers-0.1.2.0
#- ../tesths
- git: https://github.com/tosku/tesths
  commit: 988947d4b8ead71811737b44ee9ea452554d497d
- Unique-0.4.7.9
#- either-unwrap-1.1
allow-newer: true
