flags: {}
packages:
- .
extra-deps:
- natural-numbers-0.1.2.0
- git: git@github.com:tosku/tesths
  commit: a2927de94ead1a6f4235cbc202f435a575cac03a
- Unique-0.4.7.5
- either-unwrap-1.1
allow-newer: true
resolver: lts-13.1
