flags: {}
packages:
- .
extra-deps:
- natural-numbers-0.1.2.0
- git: git@github.com:tosku/tesths
  commit: fead8353b72918241d306f57126bbb5fde4eeb5a
- Unique-0.4.7.5
allow-newer: true
resolver: lts-12.18
